export const database = {
  alphabet: [
    {
      plain: "א",
      nikud: "אָלֶף",
      trans: "alef",
      ru: "Алеф",
      en: "Alef",
      fr: "Aleph",
      weight: 10,
    },
    {
      plain: "בּ",
      nikud: "בֵּית",
      trans: "bet",
      ru: "Бет",
      en: "Bet",
      fr: "Bet",
      weight: 10,
    },
    {
      plain: "ב",
      nikud: "וֵית",
      trans: "vet",
      ru: "Вет",
      en: "Vet",
      fr: "Vet",
      weight: 10,
    },
    {
      plain: "ג",
      nikud: "גִּימֶל",
      trans: "gimel",
      ru: "Гимель",
      en: "Gimel",
      fr: "Guimel",
      weight: 10,
    },
    {
      plain: "ד",
      nikud: "דָּלֶת",
      trans: "dalet",
      ru: "Далет",
      en: "Dalet",
      fr: "Dalet",
      weight: 10,
    },
    {
      plain: "ה",
      nikud: "הֵא",
      trans: "hey",
      ru: "Хей",
      en: "Hey",
      fr: "He",
      weight: 10,
    },
    {
      plain: "ו",
      nikud: "וָו",
      trans: "vav",
      ru: "Вав",
      en: "Vav",
      fr: "Vav",
      weight: 10,
    },
    {
      plain: "ז",
      nikud: "זַיִן",
      trans: "zayin",
      ru: "Заин",
      en: "Zayin",
      fr: "Zayin",
      weight: 10,
    },
    {
      plain: "ח",
      nikud: "חֵית",
      trans: "chet",
      ru: "Хет",
      en: "Chet",
      fr: "Het",
      weight: 10,
    },
    {
      plain: "ט",
      nikud: "טֵית",
      trans: "tet",
      ru: "Тет",
      en: "Tet",
      fr: "Tet",
      weight: 10,
    },
    {
      plain: "י",
      nikud: "יוֹד",
      trans: "yod",
      ru: "Йод",
      en: "Yod",
      fr: "Yod",
      weight: 10,
    },
    {
      plain: "כּ",
      nikud: "כַּף",
      trans: "kaf",
      ru: "Каф",
      en: "Kaf",
      fr: "Kaf",
      weight: 10,
    },
    {
      plain: "כ",
      nikud: "כַף",
      trans: "chaf",
      ru: "Хаф",
      en: "Chaf",
      fr: "Khaf",
      weight: 10,
    },
    {
      plain: "ך",
      nikud: "כַף סוֹפִית",
      trans: "chaf sofit",
      ru: "Хаф софит",
      en: "Chaf Sofit",
      fr: "Khaf final",
      weight: 10,
    },
    {
      plain: "ל",
      nikud: "לָמֶד",
      trans: "lamed",
      ru: "Ламед",
      en: "Lamed",
      fr: "Lamed",
      weight: 10,
    },
    {
      plain: "מ",
      nikud: "מֵם",
      trans: "mem",
      ru: "Мем",
      en: "Mem",
      fr: "Mem",
      weight: 10,
    },
    {
      plain: "ם",
      nikud: "מֵם סוֹפִית",
      trans: "mem sofit",
      ru: "Мем софит",
      en: "Mem Sofit",
      fr: "Mem final",
      weight: 10,
    },
    {
      plain: "נ",
      nikud: "נוּן",
      trans: "nun",
      ru: "Нун",
      en: "Nun",
      fr: "Noun",
      weight: 10,
    },
    {
      plain: "ן",
      nikud: "נוּן סוֹפִית",
      trans: "nun sofit",
      ru: "Нун софит",
      en: "Nun Sofit",
      fr: "Noun final",
      weight: 10,
    },
    {
      plain: "ס",
      nikud: "סָמֶךְ",
      trans: "samech",
      ru: "Самех",
      en: "Samech",
      fr: "Samekh",
      weight: 10,
    },
    {
      plain: "ע",
      nikud: "עַיִן",
      trans: "ayin",
      ru: "Аин",
      en: "Ayin",
      fr: "Ayin",
      weight: 10,
    },
    {
      plain: "פּ",
      nikud: "פֵּא",
      trans: "pey",
      ru: "Пей",
      en: "Pey",
      fr: "Pe",
      weight: 10,
    },
    {
      plain: "פ",
      nikud: "פֵא",
      trans: "fey",
      ru: "Фей",
      en: "Fey",
      fr: "Fe",
      weight: 10,
    },
    {
      plain: "ף",
      nikud: "פַא סוֹפִית",
      trans: "fey sofit",
      ru: "Фей софит",
      en: "Fey Sofit",
      fr: "Fe final",
      weight: 10,
    },
    {
      plain: "צ",
      nikud: "צָדִי",
      trans: "tsadi",
      ru: "Цади",
      en: "Tsadi",
      fr: "Tsadi",
      weight: 10,
    },
    {
      plain: "ץ",
      nikud: "צַדִי סוֹפִית",
      trans: "tsadi sofit",
      ru: "Цади софит",
      en: "Tsadi Sofit",
      fr: "Tsadi final",
      weight: 10,
    },
    {
      plain: "ק",
      nikud: "קוּף",
      trans: "kuf",
      ru: "Куф",
      en: "Kuf",
      fr: "Kouf",
      weight: 10,
    },
    {
      plain: "ר",
      nikud: "רֵישׁ",
      trans: "resh",
      ru: "Реш",
      en: "Resh",
      fr: "Resh",
      weight: 10,
    },
    {
      plain: "ש",
      nikud: "שִׁין",
      trans: "shin",
      ru: "Шин",
      en: "Shin",
      fr: "Shin",
      weight: 10,
    },
    {
      plain: "ת",
      nikud: "תָּו",
      trans: "tav",
      ru: "Тав",
      en: "Tav",
      fr: "Tav",
      weight: 10,
    },
  ],
  pronouns: [
    {
      plain: "אני",
      nikud: "אֲנִי",
      trans: "ani",
      ru: "Я",
      en: "I",
      fr: "Je",
      weight: 10,
    },
    {
      plain: "אתה",
      nikud: "אַתָּה",
      trans: "ata",
      ru: "Ты (м.р.)",
      en: "You (m.sg)",
      fr: "Tu (m)",
      weight: 10,
    },
    {
      plain: "את",
      nikud: "אַתְּ",
      trans: "at",
      ru: "Ты (ж.р.)",
      en: "You (f.sg)",
      fr: "Tu (f)",
      weight: 10,
    },
    {
      plain: "הוא",
      nikud: "הוּא",
      trans: "hu",
      ru: "Он",
      en: "He",
      fr: "Il",
      weight: 10,
    },
    {
      plain: "היא",
      nikud: "הִיא",
      trans: "hi",
      ru: "Она",
      en: "She",
      fr: "Elle",
      weight: 10,
    },
    {
      plain: "אנחנו",
      nikud: "אֲנַחְנוּ",
      trans: "anachnu",
      ru: "Мы",
      en: "We",
      fr: "Nous",
      weight: 10,
    },
    {
      plain: "אתם",
      nikud: "אַתֶּם",
      trans: "atem",
      ru: "Вы (м.р. мн.ч.)",
      en: "You (m.pl)",
      fr: "Vous (m.pl)",
      weight: 10,
    },
    {
      plain: "אתן",
      nikud: "אַתֶּן",
      trans: "aten",
      ru: "Вы (ж.р. мн.ч.)",
      en: "You (f.pl)",
      fr: "Vous (f.pl)",
      weight: 10,
    },
    {
      plain: "הם",
      nikud: "הֵם",
      trans: "hem",
      ru: "Они (м.р.)",
      en: "They (m)",
      fr: "Ils",
      weight: 10,
    },
    {
      plain: "הן",
      nikud: "הֵן",
      trans: "hen",
      ru: "Они (ж.р.)",
      en: "They (f)",
      fr: "Elles",
      weight: 10,
    },
  ],
  verbs: [
    {
      plain: "ללמוד",
      nikud: "לִלְמֹד",
      trans: "lilmod",
      ru: "Учить",
      en: "To study",
      fr: "Étudier",
      weight: 10,
      forms: [
        { plain: "לומד", nikud: "לוֹמֵד", trans: "lomed" },
        { plain: "לומדת", nikud: "לוֹמֶדֶת", trans: "lomedet" },
        { plain: "לומדים", nikud: "לוֹמְדִים", trans: "lomdim" },
        { plain: "לומדות", nikud: "לוֹמְדוֹת", trans: "lomdot" },
      ],
    },
    {
      plain: "לעבוד",
      nikud: "לַעֲבֹד",
      trans: "laavod",
      ru: "Работать",
      en: "To work",
      fr: "Travailler",
      weight: 10,
      forms: [
        { plain: "עובד", nikud: "עוֹבֵד", trans: "oved" },
        { plain: "עובדת", nikud: "עוֹבֶדֶת", trans: "ovedet" },
        { plain: "עובדים", nikud: "עוֹבְדִים", trans: "ovdim" },
        { plain: "עובדות", nikud: "עוֹבְדוֹת", trans: "ovdot" },
      ],
    },
    {
      plain: "לקרוא",
      nikud: "לִקְרֹא",
      trans: "likro",
      ru: "Читать",
      en: "To read",
      fr: "Lire",
      weight: 10,
      forms: [
        { plain: "קורא", nikud: "קוֹרֵא", trans: "kore" },
        { plain: "קוראת", nikud: "קוֹרֵאת", trans: "koret" },
        { plain: "קוראים", nikud: "קוֹרְאִים", trans: "korim" },
        { plain: "קוראות", nikud: "קוֹרְאוֹת", trans: "korot" },
      ],
    },
    {
      plain: "לכתוב",
      nikud: "לִכְתֹּב",
      trans: "lichtov",
      ru: "Писать",
      en: "To write",
      fr: "Écrire",
      weight: 10,
      forms: [
        { plain: "כותב", nikud: "כּוֹתֵב", trans: "kotev" },
        { plain: "כותבת", nikud: "כּוֹתֶבֶת", trans: "kotevet" },
        { plain: "כותבים", nikud: "כּוֹתְבִים", trans: "kotvim" },
        { plain: "כותבות", nikud: "כּוֹתְבוֹת", trans: "kotvot" },
      ],
    },
    {
      plain: "לדעת",
      nikud: "לָדַעַת",
      trans: "ladaat",
      ru: "Знать",
      en: "To know",
      fr: "Savoir",
      weight: 10,
      forms: [
        { plain: "יודע", nikud: "יוֹדֵעַ", trans: "yodea" },
        { plain: "יודעת", nikud: "יוֹדַעַת", trans: "yodaat" },
        { plain: "יודעים", nikud: "יוֹדְעִים", trans: "yodim" },
        { plain: "יודעות", nikud: "יוֹדְעוֹת", trans: "yodot" },
      ],
    },
    {
      plain: "לגור",
      nikud: "לָגוּר",
      trans: "lagur",
      ru: "Жить",
      en: "To live",
      fr: "Habiter",
      weight: 10,
      forms: [
        { plain: "גר", nikud: "גָּר", trans: "gar" },
        { plain: "גרה", nikud: "גָּרָה", trans: "gara" },
        { plain: "גרים", nikud: "גָּרִים", trans: "garim" },
        { plain: "גרות", nikud: "גָּרוֹת", trans: "garot" },
      ],
    },
    {
      plain: "לדבר",
      nikud: "לְדַבֵּר",
      trans: "ledaber",
      ru: "Говорить",
      en: "To speak",
      fr: "Parler",
      weight: 10,
      forms: [
        { plain: "מדבר", nikud: "מְדַבֵּר", trans: "medaber" },
        { plain: "מדברת", nikud: "מְדַבֶּרֶת", trans: "medaberet" },
        { plain: "מדברים", nikud: "מְדַבְּרִים", trans: "medabrim" },
        { plain: "מדברות", nikud: "מְדַבְּרוֹת", trans: "medabrot" },
      ],
    },
    {
      plain: "ללכת",
      nikud: "לָלֶכֶת",
      trans: "lalechet",
      ru: "Идти",
      en: "To walk",
      fr: "Aller",
      weight: 10,
      forms: [
        { plain: "הולך", nikud: "הוֹלֵךְ", trans: "olech" },
        { plain: "הולכת", nikud: "הוֹלֶכֶת", trans: "olechet" },
        { plain: "הולכים", nikud: "הוֹלְכִים", trans: "olchim" },
        { plain: "הולכות", nikud: "הוֹלְכוֹת", trans: "olchot" },
      ],
    },
    {
      plain: "לנסוע",
      nikud: "לִנְסֹעַ",
      trans: "linsoach",
      ru: "Ехать",
      en: "To travel",
      fr: "Voyager",
      weight: 10,
      forms: [
        { plain: "נוסע", nikud: "נוֹסֵעַ", trans: "nosea" },
        { plain: "נוסעת", nikud: "נוֹסַעַת", trans: "nosaat" },
        { plain: "נוסעים", nikud: "נוֹסְעִים", trans: "nosim" },
        { plain: "נוסעות", nikud: "נוֹסְעוֹת", trans: "nosot" },
      ],
    },
    {
      plain: "לרוץ",
      nikud: "לָרוּץ",
      trans: "laruts",
      ru: "Бежать",
      en: "To run",
      fr: "Courir",
      weight: 10,
      forms: [
        { plain: "רץ", nikud: "רָץ", trans: "rats" },
        { plain: "רצה", nikud: "רָצָה", trans: "ratsa" },
        { plain: "רצים", nikud: "רָצִים", trans: "ratsim" },
        { plain: "רצות", nikud: "רָצוֹת", trans: "ratsot" },
      ],
    },
    {
      plain: "לעמוד",
      nikud: "לַעֲמוֹד",
      trans: "laamod",
      ru: "Стоять",
      en: "To stand",
      fr: "Se tenir debout",
      weight: 10,
      forms: [
        { plain: "עומד", nikud: "עוֹמֵד", trans: "omed" },
        { plain: "עומדת", nikud: "עוֹמֶדֶת", trans: "omedet" },
        { plain: "עומדים", nikud: "עוֹמְדִים", trans: "omdim" },
        { plain: "עומדות", nikud: "עוֹמְדוֹת", trans: "omdot" },
      ],
    },
    {
      plain: "לשבת",
      nikud: "לָשֶׁבֶת",
      trans: "lashevet",
      ru: "Сидеть",
      en: "To sit",
      fr: "S'asseoir",
      weight: 10,
      forms: [
        { plain: "יושב", nikud: "יוֹשֵׁב", trans: "yoshev" },
        { plain: "יושבת", nikud: "יוֹשֶׁבֶת", trans: "yoshevet" },
        { plain: "יושבים", nikud: "יוֹשְׁבִים", trans: "yoshvim" },
        { plain: "יושבות", nikud: "יוֹשְׁבוֹת", trans: "yoshvot" },
      ],
    },
    {
      plain: "לנוח",
      nikud: "לָנוּחַ",
      trans: "lanuach",
      ru: "Отдыхать",
      en: "To rest",
      fr: "Se reposer",
      weight: 10,
      forms: [
        { plain: "נח", nikud: "נָח", trans: "nach" },
        { plain: "נחה", nikud: "נָחָה", trans: "nacha" },
        { plain: "נחים", nikud: "נָחִים", trans: "nachim" },
        { plain: "נחות", nikud: "נָחוֹת", trans: "nachot" },
      ],
    },
    {
      plain: "לקום",
      nikud: "לָקוּם",
      trans: "lakum",
      ru: "Вставать",
      en: "To wake up",
      fr: "Se lever",
      weight: 10,
      forms: [
        { plain: "קם", nikud: "קָם", trans: "kam" },
        { plain: "קמה", nikud: "קָמָה", trans: "kama" },
        { plain: "קמים", nikud: "קָמִים", trans: "kamim" },
        { plain: "קמות", nikud: "קָמוֹת", trans: "kamot" },
      ],
    },
    {
      plain: "לאכול",
      nikud: "לֶאֱכֹל",
      trans: "leechol",
      ru: "Есть",
      en: "To eat",
      fr: "Manger",
      weight: 10,
      forms: [
        { plain: "אוכל", nikud: "אוֹכֵל", trans: "ochel" },
        { plain: "אוכלת", nikud: "אוֹכֶלֶת", trans: "ochelet" },
        { plain: "אוכלים", nikud: "אוֹכְלִים", trans: "ochlim" },
        { plain: "אוכלות", nikud: "אוֹכְלוֹת", trans: "ochlot" },
      ],
    },
    {
      plain: "להרגיש",
      nikud: "לְהַרְגִּישׁ",
      trans: "lehargish",
      ru: "Чувствовать",
      en: "To feel",
      fr: "Ressentir",
      weight: 10,
      forms: [
        { plain: "מרגיש", nikud: "מַרְגִּישׁ", trans: "margish" },
        { plain: "מרגישה", nikud: "מַרְגִּישָׁה", trans: "margisha" },
        { plain: "מרגישים", nikud: "מַרְגִּישִׁים", trans: "margishim" },
        { plain: "מרגישות", nikud: "מַרְגִּישׁוֹת", trans: "margishot" },
      ],
    },
    {
      plain: "לומר",
      nikud: "לוֹמַר",
      trans: "lomar",
      ru: "Сказать",
      en: "To say",
      fr: "Dire",
      weight: 10,
      forms: [
        { plain: "אומר", nikud: "אוֹמֵר", trans: "omer" },
        { plain: "אומרת", nikud: "אוֹמֶרֶת", trans: "omeret" },
        { plain: "אומרים", nikud: "אוֹמְרִים", trans: "omrim" },
        { plain: "אומרות", nikud: "אוֹמְרוֹת", trans: "omrot" },
      ],
    },
    {
      plain: "לשאול",
      nikud: "לִשְׁאוֹל",
      trans: "lishol",
      ru: "Спрашивать",
      en: "To ask",
      fr: "Demander",
      weight: 10,
      forms: [
        { plain: "שואל", nikud: "שׁוֹאֵל", trans: "shoel" },
        { plain: "שואלת", nikud: "שׁוֹאֶלֶת", trans: "shoelet" },
        { plain: "שואלים", nikud: "שׁוֹאֲלִים", trans: "shoalim" },
        { plain: "שואלות", nikud: "שׁוֹאֲלוֹת", trans: "shoalot" },
      ],
    },
    {
      plain: "לענות",
      nikud: "לַעֲנוֹת",
      trans: "laanot",
      ru: "Отвечать",
      en: "To answer",
      fr: "Répondre",
      weight: 10,
      forms: [
        { plain: "עונה", nikud: "עוֹנֶה", trans: "one" },
        { plain: "עונה", nikud: "עוֹנָה", trans: "ona" },
        { plain: "עונים", nikud: "עוֹנִים", trans: "onim" },
        { plain: "עונות", nikud: "עוֹנוֹת", trans: "onot" },
      ],
    },
    {
      plain: "לראות",
      nikud: "לִרְאוֹת",
      trans: "lirot",
      ru: "Видеть",
      en: "To see",
      fr: "Voir",
      weight: 10,
      forms: [
        { plain: "רואה", nikud: "רוֹאֶה", trans: "roe" },
        { plain: "רואה", nikud: "רוֹאָה", trans: "roa" },
        { plain: "רואים", nikud: "רוֹאִים", trans: "roim" },
        { plain: "רואות", nikud: "רוֹאוֹת", trans: "root" },
      ],
    },
    {
      plain: "לקנות",
      nikud: "לִקְנוֹת",
      trans: "liknot",
      ru: "Покупать",
      en: "To buy",
      fr: "Acheter",
      weight: 10,
      forms: [
        { plain: "קונה", nikud: "קוֹנֶה", trans: "kone" },
        { plain: "קונה", nikud: "קוֹנָה", trans: "kona" },
        { plain: "קונים", nikud: "קוֹנִים", trans: "konim" },
        { plain: "קונות", nikud: "קוֹנוֹת", trans: "konot" },
      ],
    },
    {
      plain: "לשתות",
      nikud: "לִשְׁתּוֹת",
      trans: "lishtot",
      ru: "Пить",
      en: "To drink",
      fr: "Boire",
      weight: 10,
      forms: [
        { plain: "שותה", nikud: "שׁוֹתֶה", trans: "shote" },
        { plain: "שותה", nikud: "שׁוֹתָה", trans: "shota" },
        { plain: "שותים", nikud: "שׁוֹתִים", trans: "shotim" },
        { plain: "שותות", nikud: "שׁוֹתוֹת", trans: "shotot" },
      ],
    },
    {
      plain: "לאהוב",
      nikud: "לֶאֱהֹב",
      trans: "leehov",
      ru: "Любить",
      en: "To love",
      fr: "Aimer",
      weight: 10,
      forms: [
        { plain: "אוהב", nikud: "אוֹהֵב", trans: "ohev" },
        { plain: "אוהבת", nikud: "אוֹהֶבֶת", trans: "ohevet" },
        { plain: "אוהבים", nikud: "אוֹהֲבִים", trans: "ohavim" },
        { plain: "אוהבות", nikud: "אוֹהֲבוֹת", trans: "ohavot" },
      ],
    },
    {
      plain: "להבין",
      nikud: "לְהָבִין",
      trans: "lehavin",
      ru: "Понимать",
      en: "To understand",
      fr: "Comprendre",
      weight: 10,
      forms: [
        { plain: "מבין", nikud: "מֵבִין", trans: "mevin" },
        { plain: "מבינה", nikud: "מְבִינָה", trans: "mevina" },
        { plain: "מבינים", nikud: "מְבִינִים", trans: "mevinim" },
        { plain: "מבינות", nikud: "מְבִינוֹת", trans: "mevinot" },
      ],
    },
    {
      plain: "לרצות",
      nikud: "לִרְצוֹת",
      trans: "lirtzot",
      ru: "Хотеть",
      en: "To want",
      fr: "Vouloir",
      weight: 10,
      forms: [
        { plain: "רוצה", nikud: "רוֹצֶה", trans: "rotze" },
        { plain: "רוצה", nikud: "רוֹצָה", trans: "rotza" },
        { plain: "רוצים", nikud: "רוֹצִים", trans: "rotzim" },
        { plain: "רוצות", nikud: "רוֹצוֹת", trans: "rotzot" },
      ],
    },
    {
      plain: "לשמוע",
      nikud: "לִשְׁמֹעַ",
      trans: "lishmoa",
      ru: "Слушать",
      en: "To hear/listen",
      fr: "Entendre",
      weight: 10,
      forms: [
        { plain: "שומע", nikud: "שׁוֹמֵעַ", trans: "shomea" },
        { plain: "שומעת", nikud: "שׁוֹמַעַת", trans: "shomaat" },
        { plain: "שומעים", nikud: "שׁוֹמְעִים", trans: "shomim" },
        { plain: "שומעות", nikud: "שׁוֹמְעוֹת", trans: "shomot" },
      ],
    },
    {
      plain: "לתת",
      nikud: "לָתֵת",
      trans: "latet",
      ru: "Давать",
      en: "To give",
      fr: "Donner",
      weight: 10,
      forms: [
        { plain: "נותן", nikud: "נוֹתֵן", trans: "noten" },
        { plain: "נותנת", nikud: "נוֹתֶנֶת", trans: "notenet" },
        { plain: "נותנים", nikud: "נוֹתְנִים", trans: "notnim" },
        { plain: "נותנות", nikud: "נוֹתְנוֹת", trans: "notnot" },
      ],
    },
    {
      plain: "לקחת",
      nikud: "לָקַחַת",
      trans: "lakachat",
      ru: "Брать",
      en: "To take",
      fr: "Prendre",
      weight: 10,
      forms: [
        { plain: "לוקח", nikud: "לוֹקֵחַ", trans: "lokeach" },
        { plain: "לוקחת", nikud: "לוֹקַחַת", trans: "lokachat" },
        { plain: "לוקחים", nikud: "לוֹקְחִים", trans: "lokchim" },
        { plain: "לוקחות", nikud: "לוֹקְחוֹת", trans: "lokchot" },
      ],
    },
    {
      plain: "לפתוח",
      nikud: "לִפְתֹּחַ",
      trans: "liftoach",
      ru: "Открывать",
      en: "To open",
      fr: "Ouvrir",
      weight: 10,
      forms: [
        { plain: "פותח", nikud: "פּוֹתֵחַ", trans: "poteach" },
        { plain: "פותחת", nikud: "פּוֹתַחַת", trans: "potachat" },
        { plain: "פותחים", nikud: "פּוֹתְחִים", trans: "potchim" },
        { plain: "פותחות", nikud: "פּוֹתְחוֹת", trans: "potchot" },
      ],
    },
    {
      plain: "לסגור",
      nikud: "לִסְגֹּר",
      trans: "lisgor",
      ru: "Закрывать",
      en: "To close",
      fr: "Fermer",
      weight: 10,
      forms: [
        { plain: "סוגר", nikud: "סוֹגֵר", trans: "soger" },
        { plain: "סוגרת", nikud: "סוֹגֶרֶת", trans: "sogeret" },
        { plain: "סוגרים", nikud: "סוֹגְרִים", trans: "sogrim" },
        { plain: "סוגרות", nikud: "סוֹגְרוֹת", trans: "sogrot" },
      ],
    },
    {
      plain: "לבשל",
      nikud: "לְבַשֵּׁל",
      trans: "levashel",
      ru: "Готовить (еду)",
      en: "To cook",
      fr: "Cuisiner",
      weight: 10,
      forms: [
        { plain: "מבשל", nikud: "מְבַשֵּׁל", trans: "mevashel" },
        { plain: "מבשלת", nikud: "מְבַשֶּׁלֶת", trans: "mevashelet" },
        { plain: "מבשלים", nikud: "מְבַשְּׁלִים", trans: "mevashlim" },
        { plain: "מבשלות", nikud: "מְבַשְּׁלוֹת", trans: "mevashlot" },
      ],
    },
    {
      plain: "לשחק",
      nikud: "לְשַׂחֵק",
      trans: "lesachek",
      ru: "Играть",
      en: "To play",
      fr: "Jouer",
      weight: 10,
      forms: [
        { plain: "משחק", nikud: "מְשַׂחֵק", trans: "mesachek" },
        { plain: "משחקת", nikud: "מְשַׂחֶקֶת", trans: "mesacheket" },
        { plain: "משחקים", nikud: "מְשַׂחֲקִים", trans: "mesachkim" },
        { plain: "משחקות", nikud: "מְשַׂחֲקוֹת", trans: "mesachkot" },
      ],
    },
    {
      plain: "לחשוב",
      nikud: "לַחְשׁוֹב",
      trans: "lachshov",
      ru: "Думать",
      en: "To think",
      fr: "Penser",
      weight: 10,
      forms: [
        { plain: "חושב", nikud: "חוֹשֵׁב", trans: "choshev" },
        { plain: "חושבת", nikud: "חוֹשֶׁבֶת", trans: "choshevet" },
        { plain: "חושבים", nikud: "חוֹשְׁבִים", trans: "choshvim" },
        { plain: "חושבות", nikud: "חוֹשְׁבוֹת", trans: "choshvot" },
      ],
    },
    {
      plain: "להתקשר",
      nikud: "לְהִתְקַשֵּׁר",
      trans: "lehitkasher",
      ru: "Звонить",
      en: "To call",
      fr: "Appeler",
      weight: 10,
      forms: [
        { plain: "מתקשר", nikud: "מִתְקַשֵּׁר", trans: "mitkasher" },
        { plain: "מתקשרת", nikud: "מִתְקַשֶּׁרֶת", trans: "mitkasheret" },
        { plain: "מתקשרים", nikud: "מִתְקַשְּׁרִים", trans: "mitkashrim" },
        { plain: "מתקשרות", nikud: "מִתְקַשְּׁרוֹת", trans: "mitkashrot" },
      ],
    },
    {
      plain: "לשלוח",
      nikud: "לִשְׁלֹחַ",
      trans: "lishloach",
      ru: "Посылать",
      en: "To send",
      fr: "Envoyer",
      weight: 10,
      forms: [
        { plain: "שולח", nikud: "שׁוֹלֵחַ", trans: "sholeach" },
        { plain: "שולחת", nikud: "שׁוֹלַחַת", trans: "sholachat" },
        { plain: "שולחים", nikud: "שׁוֹלְחִים", trans: "sholchim" },
        { plain: "שולחות", nikud: "שׁוֹלְחוֹת", trans: "sholchot" },
      ],
    },
    {
      plain: "לשכוח",
      nikud: "לִשְׁכֹּחַ",
      trans: "lishkoach",
      ru: "Забывать",
      en: "To forget",
      fr: "Oublier",
      weight: 10,
      forms: [
        { plain: "שוכח", nikud: "שׁוֹכֵחַ", trans: "shocheach" },
        { plain: "שוכחת", nikud: "שׁוֹכַחַת", trans: "shochachat" },
        { plain: "שוכחים", nikud: "שׁוֹכְחִים", trans: "shochchim" },
        { plain: "שוכחות", nikud: "שׁוֹכְחוֹת", trans: "shochchot" },
      ],
    },
    {
      plain: "לזכור",
      nikud: "לִזְכֹּר",
      trans: "lizkor",
      ru: "Помнить",
      en: "To remember",
      fr: "Se souvenir",
      weight: 10,
      forms: [
        { plain: "זוכר", nikud: "זוֹכֵר", trans: "zocher" },
        { plain: "זוכרת", nikud: "זוֹכֶרֶת", trans: "zocheret" },
        { plain: "זוכרים", nikud: "זוֹכְרִים", trans: "zochrim" },
        { plain: "זוכרות", nikud: "זוֹכְרוֹת", trans: "zochrot" },
      ],
    },
    {
      plain: "לשמור",
      nikud: "לִשְׁמֹר",
      trans: "lishmor",
      ru: "Хранить",
      en: "To save/guard",
      fr: "Garder",
      weight: 10,
      forms: [
        { plain: "שומר", nikud: "שׁוֹמֵר", trans: "shomer" },
        { plain: "שומרת", nikud: "שׁוֹמֶרֶת", trans: "shomeret" },
        { plain: "שומרים", nikud: "שׁוֹמְרִים", trans: "shomrim" },
        { plain: "שומרות", nikud: "שׁוֹמְרוֹת", trans: "shomrot" },
      ],
    },
    {
      plain: "להתחיל",
      nikud: "לְהַתְחִיל",
      trans: "lehatchil",
      ru: "Начинать",
      en: "To start",
      fr: "Commencer",
      weight: 10,
      forms: [
        { plain: "מתחיל", nikud: "מַתְחִיל", trans: "matchil" },
        { plain: "מתחילה", nikud: "מַתְחִילָה", trans: "matchila" },
        { plain: "מתחילים", nikud: "מַתְחִילִים", trans: "matchilim" },
        { plain: "מתחילות", nikud: "מַתְחִילוֹת", trans: "matchilot" },
      ],
    },
  ],
  professions: [
    {
      plain: "רופא",
      nikud: "רוֹפֵא",
      trans: "rofe",
      ru: "Доктор",
      en: "Doctor",
      fr: "Médecin",
      weight: 10,
      forms: [
        { plain: "רופא", nikud: "רוֹפֵא", trans: "rofe" },
        { plain: "רופאה", nikud: "רוֹפְאָה", trans: "rofea" },
      ],
    },
    {
      plain: "שוטר",
      nikud: "שׁוֹטֵר",
      trans: "shoter",
      ru: "Полицейский",
      en: "Police officer",
      fr: "Policier",
      weight: 10,
      forms: [
        { plain: "שוטר", nikud: "שׁוֹטֵר", trans: "shoter" },
        { plain: "שוטרת", nikud: "שׁוֹטֶרֶת", trans: "shoteret" },
      ],
    },
    {
      plain: "חשמלאי",
      nikud: "חַשְׁמַלַּאי",
      trans: "hashmalay",
      ru: "Электрик",
      en: "Electrician",
      fr: "Électricien",
      weight: 10,
      forms: [
        { plain: "חשמלאי", nikud: "חַשְׁמַלַּאי", trans: "hashmalay" },
        { plain: "חשמלאית", nikud: "חַשְׁמַלָּאִית", trans: "hashmalait" },
      ],
    },
    {
      plain: "בנאי",
      nikud: "בַּנַּאי",
      trans: "banay",
      ru: "Строитель",
      en: "Builder",
      fr: "Constructeur",
      weight: 10,
      forms: [
        { plain: "בנאי", nikud: "בַּנַּאי", trans: "banay" },
        { plain: "בנאית", nikud: "בַּנָּאִית", trans: "banait" },
      ],
    },
    {
      plain: "זמר",
      nikud: "זַמָּר",
      trans: "zamar",
      ru: "Певец",
      en: "Singer",
      fr: "Chanteur",
      weight: 10,
      forms: [
        { plain: "זמר", nikud: "זַמָּר", trans: "zamar" },
        { plain: "זמרת", nikud: "זַמֶּרֶת", trans: "zameret" },
      ],
    },
    {
      plain: "מורה",
      nikud: "מוֹרֶה",
      trans: "more",
      ru: "Учитель",
      en: "Teacher",
      fr: "Professeur",
      weight: 10,
      forms: [
        { plain: "מורה", nikud: "מוֹרֶה", trans: "more" },
        { plain: "מורה", nikud: "מוֹרָה", trans: "mora" },
      ],
    },
    {
      plain: "מזכיר",
      nikud: "מַזְכִּיר",
      trans: "mazkir",
      ru: "Секретарь",
      en: "Secretary",
      fr: "Secrétaire",
      weight: 10,
      forms: [
        { plain: "מזכיר", nikud: "מַזְכִּיר", trans: "mazkir" },
        { plain: "מזכירה", nikud: "מַזְכִּירָה", trans: "mazkira" },
      ],
    },
    {
      plain: "מהנדס",
      nikud: "מְהַנְדֵּס",
      trans: "meandes",
      ru: "Инженер",
      en: "Engineer",
      fr: "Ingénieur",
      weight: 10,
      forms: [
        { plain: "מהנדס", nikud: "מְהַנְדֵּס", trans: "meandes" },
        { plain: "מהנדסת", nikud: "מְהַנְדֶּסֶת", trans: "meandeset" },
      ],
    },
    {
      plain: "עורך דין",
      nikud: "עוֹרֵךְ דִּין",
      trans: "orekh din",
      ru: "Юрист",
      en: "Lawyer",
      fr: "Avocat",
      weight: 10,
      forms: [
        { plain: "עורך דין", nikud: "עוֹרֵךְ דִּין", trans: "orekh din" },
        { plain: "עורכת דין", nikud: "עוֹרֶכֶת דִּין", trans: "orekhet din" },
      ],
    },
    {
      plain: "שחקן",
      nikud: "שַׂחְקָן",
      trans: "sahkan",
      ru: "Актер",
      en: "Actor",
      fr: "Acteur",
      weight: 10,
      forms: [
        { plain: "שחקן", nikud: "שַׂחְקָן", trans: "sahkan" },
        { plain: "שחקנית", nikud: "שַׂחְקָנִית", trans: "sahkanit" },
      ],
    },
    {
      plain: "נהג",
      nikud: "נֶהָג",
      trans: "nahag",
      ru: "Водитель",
      en: "Driver",
      fr: "Chauffeur",
      weight: 10,
      forms: [
        { plain: "נהג", nikud: "נֶהָג", trans: "nahag" },
        { plain: "נהגת", nikud: "נַהֶגֶת", trans: "naheget" },
      ],
    },
    {
      plain: "אח",
      nikud: "אָח",
      trans: "ah",
      ru: "Медбрат",
      en: "Nurse",
      fr: "Infirmier",
      weight: 10,
      forms: [
        { plain: "אח", nikud: "אָח", trans: "ah" },
        { plain: "אחות", nikud: "אָחוֹת", trans: "ahot" },
      ],
    },
    {
      plain: "ספר",
      nikud: "סַפָּר",
      trans: "sapar",
      ru: "Парикмахер",
      en: "Hairdresser",
      fr: "Coiffeur",
      weight: 10,
      forms: [
        { plain: "ספר", nikud: "סַפָּר", trans: "sapar" },
        { plain: "ספרית", nikud: "סַפָּרִית", trans: "saparit" },
      ],
    },
    {
      plain: "מוסכניק",
      nikud: "מוּסַכְנִיק",
      trans: "musakhnik",
      ru: "Автослесарь",
      en: "Auto mechanic",
      fr: "Mécanicien",
      weight: 10,
    },
    {
      plain: "מתכנת",
      nikud: "מְתַכְנֵת",
      trans: "metakhnet",
      ru: "Программист",
      en: "Programmer",
      fr: "Programmeur",
      weight: 10,
      forms: [
        { plain: "מתכנת", nikud: "מְתַכְנֵת", trans: "metakhnet" },
        { plain: "מתכנתת", nikud: "מְתַכְנֶתֶת", trans: "metakhnetet" },
      ],
    },
    {
      plain: "כבאי",
      nikud: "כַּבַּאי",
      trans: "kabay",
      ru: "Пожарный",
      en: "Firefighter",
      fr: "Pompier",
      weight: 10,
      forms: [
        { plain: "כבאי", nikud: "כַּבַּאי", trans: "kabay" },
        { plain: "כבאית", nikud: "כַּבָּאִית", trans: "kabait" },
      ],
    },
    {
      plain: "רואה חשבון",
      nikud: "רוֹאֵה חֶשְׁבּוֹן",
      trans: "ro'e heshbon",
      ru: "Бухгалтер",
      en: "Accountant",
      fr: "Comptable",
      weight: 10,
      forms: [
        {
          plain: "רואה חשבון",
          nikud: "רוֹאֵה חֶשְׁבּוֹן",
          trans: "ro'e heshbon",
        },
        {
          plain: "רואת חשבון",
          nikud: "רוֹאַת חֶשְׁבּוֹן",
          trans: "ro'at heshbon",
        },
      ],
    },
    {
      plain: "שומר",
      nikud: "שׁוֹמֵר",
      trans: "shomer",
      ru: "Охранник",
      en: "Guard",
      fr: "Gardien",
      weight: 10,
    },
  ],
  phrases: [
    {
      plain: "מה נשמע",
      nikud: "מַה נִּשְׁמַע?",
      trans: "ma nishma?",
      ru: "Как дела?",
      en: "How are you?",
      fr: "Comment ça va ?",
      weight: 10,
    },
    {
      plain: "טוב מאוד",
      nikud: "טוֹב מְאוֹד",
      trans: "tov me'od",
      ru: "Очень хорошо",
      en: "Very good",
      fr: "Très bien",
      weight: 10,
    },
    {
      plain: "הכל בסדר",
      nikud: "הַכֹּל בְּסֵדֶר",
      trans: "hakol beseder",
      ru: "Всё в порядке",
      en: "Everything is fine",
      fr: "Tout va bien",
      weight: 10,
    },
    {
      plain: "נעים מאוד",
      nikud: "נָעִים מְאוֹד",
      trans: "naim me'od",
      ru: "Очень приятно",
      en: "Nice to meet you",
      fr: "Enchanté(e)",
      weight: 10,
    },
    {
      plain: "איפה",
      nikud: "אֵיפֹה?",
      trans: "eifo?",
      ru: "Где?",
      en: "Where?",
      fr: "Où ?",
      weight: 10,
    },
    {
      plain: "שפה יפה",
      nikud: "שָׂפָה יָפָה",
      trans: "safa yafa",
      ru: "Красивый язык",
      en: "Beautiful language",
      fr: "Belle langue",
      weight: 10,
    },
    {
      plain: "עולה חדש",
      nikud: "עוֹלֶה חָדָשׁ",
      trans: "ole chadash",
      ru: "Новый репатриант",
      en: "New immigrant",
      fr: "Nouvel immigrant",
      weight: 10,
    },
    {
      plain: "אני גר בחיפה",
      nikud: "אֲנִי גָּר בְּחִיפָה",
      trans: "ani gar be-Haifa",
      ru: "Я живу в Хайфе",
      en: "I live in Haifa",
      fr: "J'habite à Haïfa",
      weight: 10,
    },
    {
      plain: "בוקר טוב",
      nikud: "בּוֹקֶר טוֹב",
      trans: "boker tov",
      ru: "Доброе утро",
      en: "Good morning",
      fr: "Bonjour",
      weight: 10,
    },
    {
      plain: "ערב טוב",
      nikud: "עֶרֶב טוֹב",
      trans: "erev tov",
      ru: "Добрый вечер",
      en: "Good evening",
      fr: "Bonsoir",
      weight: 10,
    },
    {
      plain: "תודה רבה",
      nikud: "תּוֹדָה רַבָּה",
      trans: "toda raba",
      ru: "Большое спасибо",
      en: "Thank you very much",
      fr: "Merci beaucoup",
      weight: 10,
    },
    {
      plain: "בבקשה",
      nikud: "בְּבַקָּשָׁה",
      trans: "bevakasha",
      ru: "Пожалуйста",
      en: "Please / You're welcome",
      fr: "S'il vous plaît / De rien",
      weight: 10,
    },
    {
      plain: "סליחה",
      nikud: "סְלִיחָה",
      trans: "slicha",
      ru: "Извините / Простите",
      en: "Sorry / Excuse me",
      fr: "Pardon / Excusez-moi",
      weight: 10,
    },
    {
      plain: "כמה זה עולה?",
      nikud: "כַּמָּה זֶה עוֹלֶה?",
      trans: "kama ze ole?",
      ru: "Сколько это стоит?",
      en: "How much does it cost?",
      fr: "Combien ça coûte ?",
      weight: 10,
    },
    {
      plain: "מה השעה?",
      nikud: "מַה הַשָּׁעָה?",
      trans: "ma hasha'a?",
      ru: "Который час?",
      en: "What time is it?",
      fr: "Quelle heure est-il ?",
      weight: 10,
    },
    {
      plain: "אני לא מבין",
      nikud: "אֲנִי לֹא מֵבִין",
      trans: "ani lo mevin",
      ru: "Я не понимаю (м.р.)",
      en: "I don't understand",
      fr: "Je ne comprends pas",
      weight: 10,
    },
    {
      plain: "אני לומד עברית בערב",
      nikud: "אֲנִי לוֹמֵד עִבְרִית בָּעֶרֶב",
      trans: "ani lomed ivrit ba-erev",
      ru: "Я учу иврит по вечерам",
      en: "I study Hebrew in the evening",
      fr: "J'étudie l'hébreu le soir",
      weight: 10,
    },
    {
      plain: "בהצלחה",
      nikud: "בְּהַצְלָחָה",
      trans: "behatzlacha",
      ru: "Удачи!",
      en: "Good luck!",
      fr: "Bonne chance !",
      weight: 10,
    },
    {
      plain: "להתראות",
      nikud: "לְהִתְרָאוֹת",
      trans: "lehitra'ot",
      ru: "До свидания",
      en: "Goodbye / See you later",
      fr: "Au revoir",
      weight: 10,
    },
    {
      plain: "יש לי שאלה",
      nikud: "יֵשׁ לִי שְׁאֵלָה",
      trans: "yesh li she'ela",
      ru: "У меня есть вопрос",
      en: "I have a question",
      fr: "J'ai une question",
      weight: 10,
    },
    {
      plain: "מה זה?",
      nikud: "מַה זֶּה?",
      trans: "ma ze?",
      ru: "Что это?",
      en: "What is this?",
      fr: "Qu'est-ce que c'est ?",
      weight: 10,
    },
    {
      plain: "איפה השירותים?",
      nikud: "אֵיפֹה הַשֵּׁירוּתִים?",
      trans: "eifo ha-sherutim?",
      ru: "Где туалет?",
      en: "Where is the restroom?",
      fr: "Où sont les toilettes ?",
      weight: 10,
    },
    {
      plain: "אין בעיה",
      nikud: "אֵין בְּעָיָה",
      trans: "ein be'aya",
      ru: "Нет проблем",
      en: "No problem",
      fr: "Pas de problème",
      weight: 10,
    },
    {
      plain: "אני לא יודע",
      nikud: "אֲנִי לֹא יוֹדֵעַ",
      trans: "ani lo yodea",
      ru: "Я не знаю",
      en: "I don't know",
      fr: "Je ne sais pas",
      weight: 10,
    },
    {
      plain: "אתה מדבר אנגלית?",
      nikud: "אַתָּה מְדַבֵּר אַנְגְּלִית?",
      trans: "ata medaber anglit?",
      ru: "Ты говоришь по-английски? (к мужчине)",
      en: "Do you speak English?",
      fr: "Parlez-vous anglais ?",
      weight: 10,
    },
    {
      plain: "רק קצת",
      nikud: "רַק קְצָת",
      trans: "rak ktzat",
      ru: "Только немного",
      en: "Only a little",
      fr: "Seulement un peu",
      weight: 10,
    },
    {
      plain: "אפשר לקבל...",
      nikud: "אֶפְשָׁר לְקַבֵּל...",
      trans: "efshar lekabel...",
      ru: "Можно мне... (досл. можно получить)",
      en: "Can I have...",
      fr: "Puis-je avoir...",
      weight: 10,
    },
    {
      plain: "טעים מאוד",
      nikud: "טָעִים מְאוֹד",
      trans: "taim me'od",
      ru: "Очень вкусно",
      en: "Very delicious",
      fr: "Très délicieux",
      weight: 10,
    },
    {
      plain: "איך קוראים לך?",
      nikud: "אֵיךְ קוֹרְאִים לְךָ?",
      trans: "eich korim lecha?",
      ru: "Как тебя зовут? (к мужчине)",
      en: "What is your name?",
      fr: "Comment t'appelles-tu ?",
      weight: 10,
    },
    {
      plain: "שבת שלום",
      nikud: "שַׁבָּת שָׁלוֹם",
      trans: "shabbat shalom",
      ru: "Мирной субботы / Шаббат шалом",
      en: "Peaceful Sabbath",
      fr: "Bon sabbat",
      weight: 10,
    },
    {
      plain: "בתיאבון",
      nikud: "בְּתֵיאָבוֹן",
      trans: "bete'avon",
      ru: "Приятного аппетита",
      en: "Bon appetit",
      fr: "Bon appétit",
      weight: 10,
    },
    {
      plain: "מזל טוב",
      nikud: "מַזָּל טוֹב",
      trans: "mazal tov",
      ru: "Поздравляю (Мазаль тов)",
      en: "Congratulations",
      fr: "Félicitations",
      weight: 10,
    },
    {
      plain: "ימינה",
      nikud: "יָמִינָה",
      trans: "yamina",
      ru: "Направо",
      en: "To the right",
      fr: "À droite",
      weight: 10,
    },
    {
      plain: "שמאלה",
      nikud: "שְׂמֹאלָה",
      trans: "smola",
      ru: "Налево",
      en: "To the left",
      fr: "À gauche",
      weight: 10,
    },
    {
      plain: "ישר",
      nikud: "יָשָׁר",
      trans: "yashar",
      ru: "Прямо",
      en: "Straight",
      fr: "Tout droit",
      weight: 10,
    },
  ],
  numbers: [
    {
      plain: "אפס",
      nikud: "אֶפֶס",
      trans: "efes",
      ru: "Ноль (0)",
      en: "Zero (0)",
      fr: "Zéro (0)",
      weight: 10,
    },
    {
      plain: "אחת",
      nikud: "אַחַת",
      trans: "achat",
      ru: "Одна (1)",
      en: "One (1)",
      fr: "Un (1)",
      weight: 10,
    },
    {
      plain: "שתים",
      nikud: "שְׁתַּיִם",
      trans: "shtayim",
      ru: "Две (2)",
      en: "Two (2)",
      fr: "Deux (2)",
      weight: 10,
    },
    {
      plain: "שלוש",
      nikud: "שָׁלוֹשׁ",
      trans: "shalosh",
      ru: "Три (3)",
      en: "Three (3)",
      fr: "Trois (3)",
      weight: 10,
    },
    {
      plain: "ארבע",
      nikud: "אַרְבַּע",
      trans: "arba",
      ru: "Четыре (4)",
      en: "Four (4)",
      fr: "Quatre (4)",
      weight: 10,
    },
    {
      plain: "חמש",
      nikud: "חָמֵשׁ",
      trans: "chamesh",
      ru: "Пять (5)",
      en: "Five (5)",
      fr: "Cinq (5)",
      weight: 10,
    },
    {
      plain: "שש",
      nikud: "שֵׁשׁ",
      trans: "shesh",
      ru: "Шесть (6)",
      en: "Six (6)",
      fr: "Six (6)",
      weight: 10,
    },
    {
      plain: "שבע",
      nikud: "שֶׁבַע",
      trans: "sheva",
      ru: "Семь (7)",
      en: "Seven (7)",
      fr: "Sept (7)",
      weight: 10,
    },
    {
      plain: "שמונה",
      nikud: "שְׁמוֹנֶה",
      trans: "shmone",
      ru: "Восемь (8)",
      en: "Eight (8)",
      fr: "Huit (8)",
      weight: 10,
    },
    {
      plain: "תשע",
      nikud: "תֵּשַׁע",
      trans: "tesha",
      ru: "Девять (9)",
      en: "Nine (9)",
      fr: "Neuf (9)",
      weight: 10,
    },
    {
      plain: "עשר",
      nikud: "עֶשֶׂר",
      trans: "eser",
      ru: "Десять (10)",
      en: "Ten (10)",
      fr: "Dix (10)",
      weight: 10,
    },
    {
      plain: "אחת עשרה",
      nikud: "אַחַת עֶשְׂרֵה",
      trans: "achat esre",
      ru: "Одиннадцать (11)",
      en: "Eleven (11)",
      fr: "Onze (11)",
      weight: 10,
    },
    {
      plain: "שתים עשרה",
      nikud: "שְׁתֵּים עֶשְׂרֵה",
      trans: "shteim esre",
      ru: "Двенадцать (12)",
      en: "Twelve (12)",
      fr: "Douze (12)",
      weight: 10,
    },
    {
      plain: "שלוש עשרה",
      nikud: "שְׁלוֹשׁ עֶשְׂרֵה",
      trans: "shlosh esre",
      ru: "Тринадцать (13)",
      en: "Thirteen (13)",
      fr: "Treize (13)",
      weight: 10,
    },
    {
      plain: "ארבע עשרה",
      nikud: "אַרְבַּע עֶשְׂרֵה",
      trans: "arba esre",
      ru: "Четырнадцать (14)",
      en: "Fourteen (14)",
      fr: "Quatorze (14)",
      weight: 10,
    },
    {
      plain: "חמש עשרה",
      nikud: "חֲמֵשׁ עֶשְׂרֵה",
      trans: "chamesh esre",
      ru: "Пятнадцать (15)",
      en: "Fifteen (15)",
      fr: "Quinze (15)",
      weight: 10,
    },
    {
      plain: "שש עשרה",
      nikud: "שֵׁשׁ עֶשְׂרֵה",
      trans: "shesh esre",
      ru: "Шестнадцать (16)",
      en: "Sixteen (16)",
      fr: "Seize (16)",
      weight: 10,
    },
    {
      plain: "שבע עשרה",
      nikud: "שְׁבַע עֶשְׂרֵה",
      trans: "shva esre",
      ru: "Семнадцать (17)",
      en: "Seventeen (17)",
      fr: "Dix-sept (17)",
      weight: 10,
    },
    {
      plain: "שמונה עשרה",
      nikud: "שְׁמוֹנֶה עֶשְׂרֵה",
      trans: "shmone esre",
      ru: "Восемнадцать (18)",
      en: "Eighteen (18)",
      fr: "Dix-huit (18)",
      weight: 10,
    },
    {
      plain: "תשע עשרה",
      nikud: "תְּשַׁע עֶשְׂרֵה",
      trans: "tsha esre",
      ru: "Девятнадцать (19)",
      en: "Nineteen (19)",
      fr: "Dix-neuf (19)",
      weight: 10,
    },
    {
      plain: "עשרים",
      nikud: "עֶשְׂרִים",
      trans: "esrim",
      ru: "Двадцать (20)",
      en: "Twenty (20)",
      fr: "Vingt (20)",
      weight: 10,
    },
    {
      plain: "שלושים",
      nikud: "שְׁלוֹשִׁים",
      trans: "shloshim",
      ru: "Тридцать (30)",
      en: "Thirty (30)",
      fr: "Trente (30)",
      weight: 10,
    },
    {
      plain: "ארבעים",
      nikud: "אַרְבָּעִים",
      trans: "arbaim",
      ru: "Сорок (40)",
      en: "Forty (40)",
      fr: "Quarante (40)",
      weight: 10,
    },
    {
      plain: "חמישים",
      nikud: "חֲמִישִׁים",
      trans: "chamishim",
      ru: "Пятьдесят (50)",
      en: "Fifty (50)",
      fr: "Cinquante (50)",
      weight: 10,
    },
    {
      plain: "שישים",
      nikud: "שִׁישִּׁים",
      trans: "shishim",
      ru: "Шестьдесят (60)",
      en: "Sixty (60)",
      fr: "Soixante (60)",
      weight: 10,
    },
    {
      plain: "שבעים",
      nikud: "שִׁבְעִים",
      trans: "shiv'im",
      ru: "Семьдесят (70)",
      en: "Seventy (70)",
      fr: "Soixante-dix (70)",
      weight: 10,
    },
    {
      plain: "שמונים",
      nikud: "שְׁמוֹנִים",
      trans: "shmonim",
      ru: "Восемьдесят (80)",
      en: "Eighty (80)",
      fr: "Quatre-vingts (80)",
      weight: 10,
    },
    {
      plain: "תשעים",
      nikud: "תִּשְׁעִים",
      trans: "tish'im",
      ru: "Девяносто (90)",
      en: "Ninety (90)",
      fr: "Quatre-vingt-dix (90)",
      weight: 10,
    },
    {
      plain: "מאה",
      nikud: "מֵאָה",
      trans: "mea",
      ru: "Сто (100)",
      en: "One hundred (100)",
      fr: "Cent (100)",
      weight: 10,
    },
    {
      plain: "מאה ואחת",
      nikud: "מֵאָה וְאַחַת",
      trans: "mea ve-achat",
      ru: "Сто один (101)",
      en: "One hundred and one (101)",
      fr: "Cent un (101)",
      weight: 10,
    },
    {
      plain: "מאתיים",
      nikud: "מָאתַיִם",
      trans: "matayim",
      ru: "Двести (200)",
      en: "Two hundred (200)",
      fr: "Deux cents (200)",
      weight: 10,
    },
    {
      plain: "שלוש מאות",
      nikud: "שָׁלוֹשׁ מֵאוֹת",
      trans: "shlosh meot",
      ru: "Триста (300)",
      en: "Three hundred (300)",
      fr: "Trois cents (300)",
      weight: 10,
    },
    {
      plain: "ארבע מאות",
      nikud: "אַרְבַּע מֵאוֹת",
      trans: "arba meot",
      ru: "Четыреста (400)",
      en: "Four hundred (400)",
      fr: "Quatre cents (400)",
      weight: 10,
    },
    {
      plain: "חמש מאות",
      nikud: "חֲמֵשׁ מֵאוֹת",
      trans: "chamesh meot",
      ru: "Пятьсот (500)",
      en: "Five hundred (500)",
      fr: "Cinq cents (500)",
      weight: 10,
    },
    {
      plain: "שש מאות",
      nikud: "שֵׁשׁ מֵאוֹת",
      trans: "shesh meot",
      ru: "Шестьсот (600)",
      en: "Six hundred (600)",
      fr: "Six cents (600)",
      weight: 10,
    },
    {
      plain: "שבע מאות",
      nikud: "שְׁבַע מֵאוֹת",
      trans: "shva meot",
      ru: "Семьсот (700)",
      en: "Seven hundred (700)",
      fr: "Sept cents (700)",
      weight: 10,
    },
    {
      plain: "שמונה מאות",
      nikud: "שְׁמוֹנֶה מֵאוֹת",
      trans: "shmone meot",
      ru: "Восемьсот (800)",
      en: "Eight hundred (800)",
      fr: "Huit cents (800)",
      weight: 10,
    },
    {
      plain: "תשע מאות",
      nikud: "תְּשַׁע מֵאוֹת",
      trans: "tsha meot",
      ru: "Девятьсот (900)",
      en: "Nine hundred (900)",
      fr: "Neuf cents (900)",
      weight: 10,
    },
    {
      plain: "אלף",
      nikud: "אֶלֶף",
      trans: "elef",
      ru: "Тысяча (1000)",
      en: "One thousand (1000)",
      fr: "Mille (1000)",
      weight: 10,
    },
  ],
  time: [
    {
      plain: "יום ראשון",
      nikud: "יוֹם רִאשׁוֹן",
      trans: "yom rishon",
      ru: "Воскресенье",
      en: "Sunday",
      fr: "Dimanche",
      weight: 10,
    },
    {
      plain: "יום שני",
      nikud: "יוֹם שֵׁנִי",
      trans: "yom sheni",
      ru: "Понедельник",
      en: "Monday",
      fr: "Lundi",
      weight: 10,
    },
    {
      plain: "יום שלישי",
      nikud: "יוֹם שְׁלִישִׁי",
      trans: "yom shlishi",
      ru: "Вторник",
      en: "Tuesday",
      fr: "Mardi",
      weight: 10,
    },
    {
      plain: "יום רביעי",
      nikud: "יוֹם רְבִיעִי",
      trans: "yom revii",
      ru: "Среда",
      en: "Wednesday",
      fr: "Mercredi",
      weight: 10,
    },
    {
      plain: "יום חמישי",
      nikud: "יוֹם חֲמִישִׁי",
      trans: "yom chamishi",
      ru: "Четверг",
      en: "Thursday",
      fr: "Jeudi",
      weight: 10,
    },
    {
      plain: "יום שישי",
      nikud: "יוֹם שִׁישִׁי",
      trans: "yom shishi",
      ru: "Пятница",
      en: "Friday",
      fr: "Vendredi",
      weight: 10,
    },
    {
      plain: "יום שבת",
      nikud: "יוֹם שַׁבָּת",
      trans: "yom shabbat",
      ru: "Суббота",
      en: "Saturday",
      fr: "Samedi",
      weight: 10,
    },
    {
      plain: "מחר",
      nikud: "מָחָר",
      trans: "machar",
      ru: "Завтра",
      en: "Tomorrow",
      fr: "Demain",
      weight: 10,
    },
    {
      plain: "מחרתים",
      nikud: "מָחֳרָתַיִם",
      trans: "machrataim",
      ru: "Послезавтра",
      en: "Day after tomorrow",
      fr: "Après-demain",
      weight: 10,
    },
    {
      plain: "אתמול",
      nikud: "אֶתְמוֹל",
      trans: "etmol",
      ru: "Вчера",
      en: "Yesterday",
      fr: "Hier",
      weight: 10,
    },
    {
      plain: "שלשום",
      nikud: "שִׁלְשׁוֹם",
      trans: "shilshom",
      ru: "Позавчера",
      en: "Day before yesterday",
      fr: "Avant-hier",
      weight: 10,
    },
    {
      plain: "עכשיו",
      nikud: "עַכְשָׁיו",
      trans: "achshav",
      ru: "Сейчас",
      en: "Now",
      fr: "Maintenant",
      weight: 10,
    },
    {
      plain: "תאריך",
      nikud: "תַּאֲרִיךְ",
      trans: "taarih",
      ru: "Дата",
      en: "Date",
      fr: "Date",
      weight: 10,
    },
    {
      plain: "חודש",
      nikud: "חוֹדֶשׁ",
      trans: "chodesh",
      ru: "Месяц",
      en: "Month",
      fr: "Mois",
      weight: 10,
    },
    {
      plain: "שנה",
      nikud: "שָׁנָה",
      trans: "shana",
      ru: "Год",
      en: "Year",
      fr: "Année",
      weight: 10,
    },
    {
      plain: "שעה",
      nikud: "שָׁעָה",
      trans: "shaa",
      ru: "Час",
      en: "Hour",
      fr: "Heure",
      weight: 10,
    },
    {
      plain: "מה השעה",
      nikud: "מַה הַשָּׁעָה?",
      trans: "ma hashaa?",
      ru: "Сколько времени?",
      en: "What time is it?",
      fr: "Quelle heure est-il ?",
      weight: 10,
    },
    {
      plain: "יום",
      nikud: "יוֹם",
      trans: "yom",
      ru: "День",
      en: "Day",
      fr: "Jour",
      weight: 10,
    },
    {
      plain: "ינואר",
      nikud: "יָנוּאָר",
      trans: "yanuar",
      ru: "Январь",
      en: "January",
      fr: "Janvier",
      weight: 10,
    },
    {
      plain: "פברואר",
      nikud: "פֶבְּרוּאָר",
      trans: "fevruar",
      ru: "Февраль",
      en: "February",
      fr: "Février",
      weight: 10,
    },
    {
      plain: "מרץ",
      nikud: "מֶרְץ",
      trans: "merts",
      ru: "Март",
      en: "March",
      fr: "Mars",
      weight: 10,
    },
    {
      plain: "אפריל",
      nikud: "אַפְּרִיל",
      trans: "april",
      ru: "Апрель",
      en: "April",
      fr: "Avril",
      weight: 10,
    },
    {
      plain: "מאי",
      nikud: "מַאי",
      trans: "mai",
      ru: "Май",
      en: "May",
      fr: "Mai",
      weight: 10,
    },
    {
      plain: "יוני",
      nikud: "יוּנִי",
      trans: "yuni",
      ru: "Июнь",
      en: "June",
      fr: "Juin",
      weight: 10,
    },
    {
      plain: "יולי",
      nikud: "יוּלִי",
      trans: "yuli",
      ru: "Июль",
      en: "July",
      fr: "Juillet",
      weight: 10,
    },
    {
      plain: "אוגוסט",
      nikud: "אוֹגוּסְט",
      trans: "ogust",
      ru: "Август",
      en: "August",
      fr: "Août",
      weight: 10,
    },
    {
      plain: "ספטמבר",
      nikud: "סֶפְּטֶמְבֶּר",
      trans: "september",
      ru: "Сентябрь",
      en: "September",
      fr: "Septembre",
      weight: 10,
    },
    {
      plain: "אוקטובר",
      nikud: "אוֹקְטוֹבֶּר",
      trans: "oktover",
      ru: "Октябрь",
      en: "October",
      fr: "Octobre",
      weight: 10,
    },
    {
      plain: "נובמבר",
      nikud: "נוֹבֶמְבֶּר",
      trans: "november",
      ru: "Ноябрь",
      en: "November",
      fr: "Novembre",
      weight: 10,
    },
    {
      plain: "דצמבר",
      nikud: "דֶּצֶמְבֶּר",
      trans: "detsember",
      ru: "Декабрь",
      en: "December",
      fr: "Décembre",
      weight: 10,
    },
  ],
  objects: [
    {
      plain: "אוזניים",
      nikud: "אָזְנַיִם",
      trans: "oznayim",
      ru: "Наушники",
      en: "Headphones",
      fr: "Écouteurs",
      weight: 10,
      forms: [
        { plain: "אוזניים", nikud: "אָזְנַיִם", trans: "oznayim" },
        { plain: "אוזנייה", nikud: "אוֹזְנִיָּה", trans: "ozniya" },
      ],
    },
    {
      plain: "ארון",
      nikud: "אָרוֹן",
      trans: "aron",
      ru: "Шкаф",
      en: "Closet",
      fr: "Armoire",
      weight: 10,
    },
    {
      plain: "דלת",
      nikud: "דֶּלֶת",
      trans: "delet",
      ru: "Дверь",
      en: "Door",
      fr: "Porte",
      weight: 10,
    },
    {
      plain: "הפסקה",
      nikud: "הַפְסָקָה",
      trans: "hafsaka",
      ru: "Перерыв",
      en: "Break",
      fr: "Pause",
      weight: 10,
    },
    {
      plain: "חלון",
      nikud: "חַלּוֹן",
      trans: "chalon",
      ru: "Окно",
      en: "Window",
      fr: "Fenêtre",
      weight: 10,
    },
    {
      plain: "וילון",
      nikud: "וִילוֹן",
      trans: "vilon",
      ru: "Штора",
      en: "Curtain",
      fr: "Rideau",
      weight: 10,
    },
    {
      plain: "שטיח",
      nikud: "שָׁטִיחַ",
      trans: "shatiach",
      ru: "Ковер",
      en: "Carpet",
      fr: "Tapis",
      weight: 10,
    },
    {
      plain: "חדר",
      nikud: "חֶדֶר",
      trans: "cheder",
      ru: "Комната",
      en: "Room",
      fr: "Chambre",
      weight: 10,
    },
    {
      plain: "שמים",
      nikud: "שָׁמַיִם",
      trans: "shamaim",
      ru: "Небо",
      en: "Sky",
      fr: "Ciel",
      weight: 10,
    },
    {
      plain: "טלוויזיה",
      nikud: "טֵלֵוִויזְיָה",
      trans: "televizia",
      ru: "Телевизор",
      en: "Television",
      fr: "Télévision",
      weight: 10,
    },
    {
      plain: "שמש",
      nikud: "שֶׁמֶשׁ",
      trans: "shemesh",
      ru: "Солнце",
      en: "Sun",
      fr: "Soleil",
      weight: 10,
    },
    {
      plain: "ילד",
      nikud: "יֶלֶד",
      trans: "yeled",
      ru: "Мальчик",
      en: "Boy",
      fr: "Garçon",
      weight: 10,
      forms: [
        { plain: "ילד", nikud: "יֶלֶד", trans: "yeled" },
        { plain: "ילדה", nikud: "יַלְדָּה", trans: "yalda" },
      ],
    },
    {
      plain: "כיסא",
      nikud: "כִּסֵּא",
      trans: "kise",
      ru: "Стул",
      en: "Chair",
      fr: "Chaise",
      weight: 10,
    },
    {
      plain: "לוח",
      nikud: "לוּחַ",
      trans: "luach",
      ru: "Доска",
      en: "Board",
      fr: "Tableau",
      weight: 10,
    },
    {
      plain: "מבחן",
      nikud: "מִבְחָן",
      trans: "mivchan",
      ru: "Экзамен",
      en: "Exam",
      fr: "Examen",
      weight: 10,
    },
    {
      plain: "מזגן",
      nikud: "מַזְגָן",
      trans: "mazgan",
      ru: "Кондиционер",
      en: "Air conditioner",
      fr: "Climatiseur",
      weight: 10,
    },
    {
      plain: "מחשב",
      nikud: "מַחְשֵׁב",
      trans: "machshev",
      ru: "Компьютер",
      en: "Computer",
      fr: "Ordinateur",
      weight: 10,
    },
    {
      plain: "מסך",
      nikud: "מָסָךְ",
      trans: "masach",
      ru: "Экран",
      en: "Screen",
      fr: "Écran",
      weight: 10,
    },
    {
      plain: "מפעל",
      nikud: "מִפְעָל",
      trans: "mifal",
      ru: "Завод",
      en: "Factory",
      fr: "Usine",
      weight: 10,
    },
    {
      plain: "מילון",
      nikud: "מִילּוֹן",
      trans: "milon",
      ru: "Словарь",
      en: "Dictionary",
      fr: "Dictionnaire",
      weight: 10,
    },
    {
      plain: "מילה",
      nikud: "מִילָּה",
      trans: "mila",
      ru: "Слово",
      en: "Word",
      fr: "Mot",
      weight: 10,
    },
    {
      plain: "משפט",
      nikud: "מִשְׁפָּט",
      trans: "mishpat",
      ru: "Предложение",
      en: "Sentence",
      fr: "Phrase",
      weight: 10,
    },
    {
      plain: "עיתון",
      nikud: "עִיתּוֹן",
      trans: "iton",
      ru: "Газета",
      en: "Newspaper",
      fr: "Journal",
      weight: 10,
    },
    {
      plain: "מקלדת",
      nikud: "מִקְלֶדֶת",
      trans: "mikledet",
      ru: "Клавиатура",
      en: "Keyboard",
      fr: "Clavier",
      weight: 10,
    },
    {
      plain: "עט",
      nikud: "עֵט",
      trans: "et",
      ru: "Ручка",
      en: "Pen",
      fr: "Stylo",
      weight: 10,
    },
    {
      plain: "עיפרון",
      nikud: "עִיפָּרוֹן",
      trans: "iparon",
      ru: "Карандаш",
      en: "Pencil",
      fr: "Crayon",
      weight: 10,
    },
    {
      plain: "עכבר",
      nikud: "עַכְבָּר",
      trans: "akhbar",
      ru: "Мышь",
      en: "Mouse",
      fr: "Souris",
      weight: 10,
    },
    {
      plain: "פארק",
      nikud: "פַּארְק",
      trans: "park",
      ru: "Парк",
      en: "Park",
      fr: "Parc",
      weight: 10,
    },
    {
      plain: "ספסל",
      nikud: "סַפְסָל",
      trans: "safsal",
      ru: "Скамейка",
      en: "Bench",
      fr: "Banc",
      weight: 10,
    },
    {
      plain: "דשא",
      nikud: "דֶּשֶׁא",
      trans: "deshe",
      ru: "Трава",
      en: "Grass",
      fr: "Herbe",
      weight: 10,
    },
    {
      plain: "דרך",
      nikud: "דֶּרֶךְ",
      trans: "derekh",
      ru: "Дорога",
      en: "Road",
      fr: "Route",
      weight: 10,
    },
    {
      plain: "רדיו",
      nikud: "רַדְיוֹ",
      trans: "radio",
      ru: "Радио",
      en: "Radio",
      fr: "Radio",
      weight: 10,
    },
    {
      plain: "שולחן",
      nikud: "שׁוּלְחָן",
      trans: "shulchan",
      ru: "Стол",
      en: "Table",
      fr: "Table",
      weight: 10,
    },
    {
      plain: "תיק",
      nikud: "תִּיק",
      trans: "tik",
      ru: "Сумка",
      en: "Bag",
      fr: "Sac",
      weight: 10,
    },
    {
      plain: "תמונה",
      nikud: "תְּמוּנָה",
      trans: "tmuna",
      ru: "Картина",
      en: "Picture",
      fr: "Image",
      weight: 10,
    },
    {
      plain: "עץ",
      nikud: "עֵץ",
      trans: "ets",
      ru: "Дерево",
      en: "Tree",
      fr: "Arbre",
      weight: 10,
    },
    {
      plain: "ספה",
      nikud: "סַפָּה",
      trans: "sapa",
      ru: "Диван",
      en: "Sofa",
      fr: "Canapé",
      weight: 10,
    },
    {
      plain: "מפה",
      nikud: "מַפָּה",
      trans: "mapa",
      ru: "Карта",
      en: "Map",
      fr: "Carte",
      weight: 10,
    },
    {
      plain: "מכונית",
      nikud: "מְכוֹנִית",
      trans: "mechonit",
      ru: "Машина",
      en: "Car",
      fr: "Voiture",
      weight: 10,
    },
    {
      plain: "סיפור",
      nikud: "סִיפּוּר",
      trans: "sipur",
      ru: "Рассказ",
      en: "Story",
      fr: "Histoire",
      weight: 10,
    },
    {
      plain: "דירה",
      nikud: "דִּירָה",
      trans: "dira",
      ru: "Квартира",
      en: "Apartment",
      fr: "Appartement",
      weight: 10,
    },
    {
      plain: "חתול",
      nikud: "חָתוּל",
      trans: "chatul",
      ru: "Кот",
      en: "Cat",
      fr: "Chat",
      weight: 10,
    },
    {
      plain: "בקבוק",
      nikud: "בַּקְבּוּק",
      trans: "bakbuk",
      ru: "Бутылка",
      en: "Bottle",
      fr: "Bouteille",
      weight: 10,
    },
    {
      plain: "סוד",
      nikud: "סוֹד",
      trans: "sod",
      ru: "Секрет",
      en: "Secret",
      fr: "Secret",
      weight: 10,
    },
    {
      plain: "אוטובוס",
      nikud: "אוֹטוֹבּוּס",
      trans: "otobus",
      ru: "Автобус",
      en: "Bus",
      fr: "Bus",
      weight: 10,
    },
  ],
  colors: [
    {
      plain: "אדום",
      nikud: "אָדוֹם",
      trans: "adom",
      ru: "Красный",
      en: "Red",
      fr: "Rouge",
      weight: 10,
      forms: [
        { plain: "אדום", nikud: "אָדוֹם", trans: "adom" },
        { plain: "אדומה", nikud: "אֲדוּמָה", trans: "aduma" },
        { plain: "אדומים", nikud: "אֲדוּמִים", trans: "adumim" },
        { plain: "אדומות", nikud: "אֲדוּמוֹת", trans: "adumot" },
      ],
    },
    {
      plain: "כחול",
      nikud: "כָּחוֹל",
      trans: "kachol",
      ru: "Синий",
      en: "Blue",
      fr: "Bleu",
      weight: 10,
      forms: [
        { plain: "כחול", nikud: "כָּחוֹל", trans: "kachol" },
        { plain: "כחולה", nikud: "כְּחוּלָה", trans: "kchula" },
        { plain: "כחולים", nikud: "כְּחוּלִים", trans: "kchulim" },
        { plain: "כחולות", nikud: "כְּחוּלוֹת", trans: "kchulot" },
      ],
    },
    {
      plain: "ירוק",
      nikud: "יָרוֹק",
      trans: "yarok",
      ru: "Зеленый",
      en: "Green",
      fr: "Vert",
      weight: 10,
      forms: [
        { plain: "ירוק", nikud: "יָרוֹק", trans: "yarok" },
        { plain: "ירוקה", nikud: "יְרוּקָה", trans: "yeruka" },
        { plain: "ירוקים", nikud: "יְרוּקִים", trans: "yerukim" },
        { plain: "ירוקות", nikud: "יְרוּקוֹת", trans: "yerukot" },
      ],
    },
    {
      plain: "צהוב",
      nikud: "צָהוֹב",
      trans: "tzahov",
      ru: "Желтый",
      en: "Yellow",
      fr: "Jaune",
      weight: 10,
      forms: [
        { plain: "צהוב", nikud: "צָהוֹב", trans: "tzahov" },
        { plain: "צהובה", nikud: "צְהוּבָּה", trans: "tzehuva" },
        { plain: "צהובים", nikud: "צְהוּבִּים", trans: "tzehuvim" },
        { plain: "צהובות", nikud: "צְהוּבּוֹת", trans: "tzehuvot" },
      ],
    },
    {
      plain: "לבן",
      nikud: "לָבָן",
      trans: "lavan",
      ru: "Белый",
      en: "White",
      fr: "Blanc",
      weight: 10,
      forms: [
        { plain: "לבן", nikud: "לָבָן", trans: "lavan" },
        { plain: "לבנה", nikud: "לְבָנָה", trans: "levana" },
        { plain: "לבנים", nikud: "לְבָנִים", trans: "levanim" },
        { plain: "לבנות", nikud: "לְבָנוֹת", trans: "levanot" },
      ],
    },
    {
      plain: "שחור",
      nikud: "שָׁחוֹר",
      trans: "shachor",
      ru: "Черный",
      en: "Black",
      fr: "Noir",
      weight: 10,
      forms: [
        { plain: "שחור", nikud: "שָׁחוֹר", trans: "shachor" },
        { plain: "שחורה", nikud: "שְׁחוֹרָה", trans: "shchora" },
        { plain: "שחורים", nikud: "שְׁחוֹרִים", trans: "shchorim" },
        { plain: "שחורות", nikud: "שְׁחוֹרוֹת", trans: "shchorot" },
      ],
    },
    {
      plain: "חום",
      nikud: "חוּם",
      trans: "chum",
      ru: "Коричневый",
      en: "Brown",
      fr: "Marron",
      weight: 10,
      forms: [
        { plain: "חום", nikud: "חוּם", trans: "chum" },
        { plain: "חומה", nikud: "חוּמָה", trans: "chuma" },
        { plain: "חומים", nikud: "חוּמִים", trans: "chumim" },
        { plain: "חומות", nikud: "חוּמוֹת", trans: "chumot" },
      ],
    },
    {
      plain: "ורוד",
      nikud: "וָרוֹד",
      trans: "varod",
      ru: "Розовый",
      en: "Pink",
      fr: "Rose",
      weight: 10,
      forms: [
        { plain: "ורוד", nikud: "וָרוֹד", trans: "varod" },
        { plain: "ורודה", nikud: "וְרוּדָה", trans: "vruda" },
        { plain: "ורודים", nikud: "וְרוּדִים", trans: "vrudim" },
        { plain: "ורודות", nikud: "וְרוּדוֹת", trans: "vrudot" },
      ],
    },
    {
      plain: "סגול",
      nikud: "סָגוֹל",
      trans: "sagol",
      ru: "Фиолетовый",
      en: "Purple",
      fr: "Violet",
      weight: 10,
      forms: [
        { plain: "סגול", nikud: "סָגוֹל", trans: "sagol" },
        { plain: "סגולה", nikud: "סְגוּלָה", trans: "sgula" },
        { plain: "סגולים", nikud: "סְגוּלִים", trans: "sgulim" },
        { plain: "סגולות", nikud: "סְגוּלוֹת", trans: "sgulot" },
      ],
    },
    {
      plain: "כתום",
      nikud: "כָּתוֹם",
      trans: "katom",
      ru: "Оранжевый",
      en: "Orange",
      fr: "Orange",
      weight: 10,
      forms: [
        { plain: "כתום", nikud: "כָּתוֹם", trans: "katom" },
        { plain: "כתומה", nikud: "כְּתוּמָה", trans: "ktuma" },
        { plain: "כתומים", nikud: "כְּתוּמִים", trans: "ktumim" },
        { plain: "כתומות", nikud: "כְּתוּמוֹת", trans: "ktumot" },
      ],
    },
    {
      plain: "אפור",
      nikud: "אָפוֹר",
      trans: "afor",
      ru: "Серый",
      en: "Gray",
      fr: "Gris",
      weight: 10,
      forms: [
        { plain: "אפור", nikud: "אָפוֹר", trans: "afor" },
        { plain: "אפורה", nikud: "אֲפוֹרָה", trans: "efora" },
        { plain: "אפורים", nikud: "אֲפוֹרִים", trans: "eforim" },
        { plain: "אפורות", nikud: "אֲפוֹרוֹת", trans: "eforot" },
      ],
    },
    {
      plain: "תכלת",
      nikud: "תְּכֵלֶת",
      trans: "tchelet",
      ru: "Светло-голубой",
      en: "Light blue",
      fr: "Bleu clair",
      weight: 10,
      forms: [
        { plain: "תכלת", nikud: "תְּכֵלֶת", trans: "tchelet" },
        { plain: "תכלת", nikud: "תְּכֵלֶת", trans: "tchelet" },
        { plain: "תכלת", nikud: "תְּכֵלֶת", trans: "tchelet" },
        { plain: "תכלת", nikud: "תְּכֵלֶת", trans: "tchelet" },
      ],
    },
    {
      plain: "צבעוני",
      nikud: "צִבְעוֹנִי",
      trans: "tziv'oni",
      ru: "Цветной",
      en: "Colorful",
      fr: "Coloré",
      weight: 10,
      forms: [
        { plain: "צבעוני", nikud: "צִבְעוֹנִי", trans: "tziv'oni" },
        { plain: "צבעונית", nikud: "צִבְעוֹנִית", trans: "tziv'onit" },
        { plain: "צבעוניים", nikud: "צִבְעוֹנִיִּים", trans: "tziv'oniyim" },
        { plain: "צבעוניות", nikud: "צִבְעוֹנִיּוֹת", trans: "tziv'oniyot" },
      ],
    },
    {
      plain: "כהה",
      nikud: "כֵּהֶה",
      trans: "kehe",
      ru: "Темный",
      en: "Dark",
      fr: "Foncé",
      weight: 10,
      forms: [
        { plain: "כהה", nikud: "כֵּהֶה", trans: "kehe" },
        { plain: "כהה", nikud: "כֵּהָה", trans: "keha" },
        { plain: "כהים", nikud: "כֵּהִים", trans: "kehim" },
        { plain: "כהות", nikud: "כֵּהוֹת", trans: "kehot" },
      ],
    },
    {
      plain: "בהיר",
      nikud: "בָּהִיר",
      trans: "bahir",
      ru: "Светлый",
      en: "Light",
      fr: "Clair",
      weight: 10,
      forms: [
        { plain: "בהיר", nikud: "בָּהִיר", trans: "bahir" },
        { plain: "בהירה", nikud: "בְּהִירָה", trans: "behira" },
        { plain: "בהירים", nikud: "בְּהִירִים", trans: "behirim" },
        { plain: "בהירות", nikud: "בְּהִירוֹת", trans: "behirot" },
      ],
    },
    {
      plain: "זהוב",
      nikud: "זָהוּב",
      trans: "zahuv",
      ru: "Золотистый",
      en: "Golden",
      fr: "Doré",
      weight: 10,
      forms: [
        { plain: "זהוב", nikud: "זָהוּב", trans: "zahuv" },
        { plain: "זהובה", nikud: "זְהוּבָה", trans: "zehuva" },
        { plain: "זהובים", nikud: "זְהוּבִים", trans: "zehuvim" },
        { plain: "זהובות", nikud: "זְהוּבוֹת", trans: "zehuvot" },
      ],
    },
    {
      plain: "כסוף",
      nikud: "כָּסוּף",
      trans: "kasuf",
      ru: "Серебристый",
      en: "Silvery",
      fr: "Argenté",
      weight: 10,
      forms: [
        { plain: "כסוף", nikud: "כָּסוּף", trans: "kasuf" },
        { plain: "כסופה", nikud: "כְּסוּפָה", trans: "ksufa" },
        { plain: "כסופים", nikud: "כְּסוּפִים", trans: "ksufim" },
        { plain: "כסופות", nikud: "כְּסוּפוֹת", trans: "ksufot" },
      ],
    },
    {
      plain: "אדמדם",
      nikud: "אֲדַמְדַּם",
      trans: "adamdam",
      ru: "Красноватый",
      en: "Reddish",
      fr: "Rougeâtre",
      weight: 10,
      forms: [
        { plain: "אדמדם", nikud: "אֲדַמְדַּם", trans: "adamdam" },
        { plain: "אדמדמה", nikud: "אֲדַמְדַּמָּה", trans: "adamdama" },
        { plain: "אדמדמים", nikud: "אֲדַמְדַּמִּים", trans: "adamdamim" },
        { plain: "אדמדמות", nikud: "אֲדַמְדַּמּוֹת", trans: "adamdamot" },
      ],
    },
    {
      plain: "ירקרק",
      nikud: "יְרַקְרַק",
      trans: "yerakrak",
      ru: "Зеленоватый",
      en: "Greenish",
      fr: "Verdâtre",
      weight: 10,
      forms: [
        { plain: "ירקרק", nikud: "יְרַקְרַק", trans: "yerakrak" },
        { plain: "ירקרקה", nikud: "יְרַקְרַקָּה", trans: "yerakraka" },
        { plain: "ירקרקים", nikud: "יְרַקְרַקִּים", trans: "yerakrakim" },
        { plain: "ירקרקות", nikud: "יְרַקְרַקּוֹת", trans: "yerakrakot" },
      ],
    },
    {
      plain: "כחלחל",
      nikud: "כְּחַלְחַל",
      trans: "kchalchal",
      ru: "Синеватый",
      en: "Bluish",
      fr: "Bleuâtre",
      weight: 10,
      forms: [
        { plain: "כחלחל", nikud: "כְּחַלְחַל", trans: "kchalchal" },
        { plain: "כחלחלה", nikud: "כְּחַלְחַלָּה", trans: "kchalchala" },
        { plain: "כחלחלים", nikud: "כְּחַלְחַלִּים", trans: "kchalchalim" },
        { plain: "כחלחלות", nikud: "כְּחַלְחַלּוֹת", trans: "kchalchalot" },
      ],
    },
  ],
  custom: [],
};

export const locales = {
  ru: {
    title: "Что будем изучать?",
    abc: "Алфавит",
    pronouns: "Местоимения",
    verbs: "Глаголы",
    professions: "Профессии",
    phrases: "Фразы",
    numbers: "Числа",
    time: "Время и даты",
    objects: "Дом и предметы",
    custom: "Мои слова",
    showHint: "Показать некудот",
    gameMode: "Тренажер",
    typeMode: "Письмо",
    viewMode: "Листалка",
    library: "Библиотека",
    libraryTitle: "Библиотека",
    libAlphabet: "Абв",
    libPronouns: "Мест.",
    libVerbs: "Глаголы",
    libProfessions: "Проф.",
    libPhrases: "Фразы",
    libNumbers: "Числа",
    libTime: "Время",
    libObjects: "Дом",
    libCustom: "Мои",
    searchPlaceholder: "Поиск слова...",
    resultsTitle: "Раунд завершен!",
    correct: "Правильно",
    wrong: "Ошибки",
    backToMenu: "В меню",
    back: "Назад",
    forward: "Вперед",
    emptyFolder: "Работа над ошибками (Пусто)",
    folder: "Работа над ошибками",
    addWordBtn: "Добавить свое слово",
    addWordTitle: "Создать карточку",
    editWordBtn: "Редактировать",
    editWordTitle: "Редактировать карточку",
    formPlain: "Слово на иврите (Обязательно)*",
    formNikud: "Слово с огласовками",
    formTrans: "Транскрипция",
    formRu: "Перевод на Русский (Обязательно)*",
    formEn: "Перевод на English",
    formFr: "Перевод на Français",
    saveBtn: "Сохранить слово",
    deleteBtn: "Удалить",
    errorCustomMin: "Добавьте минимум 4 слова для тренировки!",
    phPlain: "Например: שָׁלוֹם или שלום",
    phNikud: "Например: שָׁלוֹם",
    phTrans: "Например: shalom",
    phRu: "Привет / Мир",
    phEn: "Hello / Peace",
    phFr: "Bonjour / Paix",
    taskVerbForm: "Выберите правильную форму:",
    checkBtn: "Проверить",
    typePlaceholder: "Напишите на иврите...",
    catColors: "Цвета",
    libColors: "Цвета",
  },
  en: {
    title: "What do you want to learn?",
    abc: "Alphabet",
    pronouns: "Pronouns",
    verbs: "Verbs",
    professions: "Professions",
    phrases: "Phrases",
    numbers: "Numbers",
    time: "Time & Dates",
    objects: "Environment",
    custom: "My Words",
    showHint: "Show Answer",
    gameMode: "Trainer",
    typeMode: "Type",
    viewMode: "List View",
    library: "Library",
    libraryTitle: "Library",
    libAbc: "ABC",
    libPronouns: "Pron.",
    libVerbs: "Verbs",
    libProfessions: "Prof.",
    libPhrases: "Phrases",
    libNumbers: "Numbers",
    libTime: "Time",
    libObjects: "Home",
    libCustom: "Mine",
    searchPlaceholder: "Search word...",
    resultsTitle: "Round Complete!",
    correct: "Correct",
    wrong: "Mistakes",
    backToMenu: "Menu",
    back: "Back",
    forward: "Forward",
    emptyFolder: "Error Correction (Empty)",
    folder: "Error Correction",
    addWordBtn: "Add Custom Word",
    addWordTitle: "Create Flashcard",
    editWordBtn: "Edit",
    editWordTitle: "Edit Flashcard",
    formPlain: "Hebrew Word (Required)*",
    formNikud: "Word with Vowels",
    formTrans: "Transliteration",
    formRu: "Russian Translation (Required)*",
    formEn: "English Translation",
    formFr: "French Translation",
    saveBtn: "Save Word",
    deleteBtn: "Delete",
    errorCustomMin: "Add at least 4 words to practice!",
    phPlain: "E.g.: שָׁלוֹם or שלום",
    phNikud: "E.g.: שָׁלוֹם",
    phTrans: "E.g.: shalom",
    phRu: "Привет / Мир",
    phEn: "Hello / Peace",
    phFr: "Bonjour / Paix",
    taskVerbForm: "Choose the correct form:",
    checkBtn: "Check",
    typePlaceholder: "Type in Hebrew...",
    catColors: "Colors",
    libColors: "Colors",
  },
  fr: {
    title: "Que voulez-vous apprendre ?",
    abc: "Alphabet",
    pronouns: "Pronoms",
    verbs: "Verbes",
    professions: "Professions",
    phrases: "Phrases",
    numbers: "Nombres",
    time: "Temps et Dates",
    objects: "Maison et Objets",
    custom: "Mes mots",
    showHint: "Afficher la réponse",
    gameMode: "Entraîneur",
    typeMode: "Écrire",
    viewMode: "Liste",
    library: "Bibliothèque",
    libraryTitle: "Bibliothèque",
    libAbc: "ABC",
    libPronouns: "Pron.",
    libVerbs: "Verbes",
    libProfessions: "Prof.",
    libPhrases: "Phrases",
    libNumbers: "Nombres",
    libTime: "Temps",
    libObjects: "Maison",
    libCustom: "Mien",
    searchPlaceholder: "Chercher un mot...",
    resultsTitle: "Manche terminée !",
    correct: "Correct",
    wrong: "Erreurs",
    backToMenu: "Menu",
    back: "Retour",
    forward: "Suivant",
    emptyFolder: "Correction (Vide)",
    folder: "Correction",
    addWordBtn: "Ajouter un mot",
    addWordTitle: "Créer une carte",
    editWordBtn: "Modifier",
    editWordTitle: "Modifier la carte",
    formPlain: "Mot hébreu (Requis)*",
    formNikud: "Mot avec voyelles",
    formTrans: "Translittération",
    formRu: "Traduction Russe (Requis)*",
    formEn: "Traduction Anglaise",
    formFr: "Traduction Française",
    saveBtn: "Enregistrer le mot",
    deleteBtn: "Supprimer",
    errorCustomMin: "Ajoutez au moins 4 mots pour vous entraîner !",
    phPlain: "Ex. : שָׁלוֹם ou שלום",
    phNikud: "Ex. : שָׁלוֹם",
    phTrans: "Ex. : shalom",
    phRu: "Привет / Мир",
    phEn: "Hello / Peace",
    phFr: "Bonjour / Paix",
    taskVerbForm: "Choisissez la forme correcte :",
    checkBtn: "Vérifier",
    typePlaceholder: "Écrivez en hébreu...",
    catColors: "Couleurs",
    libColors: "Couleurs",
  },
};
